CRITICAL - 2022-11-09 22:58:47 --> The namespace delimiter is a backslash (\), not a slash (/). Route handler: \App\Controllers\API\Clientes:edit/$1
in SYSTEMPATH\Router\Router.php on line 466.
 1 SYSTEMPATH\Router\Router.php(466): CodeIgniter\Router\Exceptions\RouterException::forInvalidControllerName('\\App\\Controllers\\API\\Clientes:edit/$1')
 2 SYSTEMPATH\Router\Router.php(181): CodeIgniter\Router\Router->checkRoutes('api/clientes/1')
 3 SYSTEMPATH\CodeIgniter.php(802): CodeIgniter\Router\Router->handle('api/clientes/1')
 4 SYSTEMPATH\CodeIgniter.php(430): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-09 23:40:19 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `venta` ...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `venta` ...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `venta` ...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `venta` ...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(46): CodeIgniter\Model->update('1', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->editar('1')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-09 23:40:25 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `venta` ...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `venta` ...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `venta` ...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `venta` ...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(46): CodeIgniter\Model->update('1', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->editar('1')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-09 23:41:55 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `ve...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ve...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ve...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ve...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(23): CodeIgniter\Model->insert(Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->crear()
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-09 23:41:59 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `ve...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ve...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ve...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ve...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(23): CodeIgniter\Model->insert(Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->crear()
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-09 23:42:12 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `ve...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ve...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ve...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ve...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(23): CodeIgniter\Model->insert(Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->crear()
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-09 23:42:17 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `ve...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ve...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ve...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ve...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(23): CodeIgniter\Model->insert(Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->crear()
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-09 23:43:55 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Facturas.php(23): CodeIgniter\Model->insert(Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Facturas->crear()
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Facturas))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-09 23:44:02 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Facturas.php(23): CodeIgniter\Model->insert(Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Facturas->crear()
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Facturas))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-09 23:47:18 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `factura...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `factura...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `factura...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `factura...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Facturas.php(46): CodeIgniter\Model->update('1', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Facturas->editar('1')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Facturas))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-09 23:59:50 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `venta` ...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `venta` ...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `venta` ...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `venta` ...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(46): CodeIgniter\Model->update('1', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->editar('1')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-09 23:59:59 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `venta` ...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `venta` ...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `venta` ...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `venta` ...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(46): CodeIgniter\Model->update('1', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->editar('1')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
