ERROR - 2022-11-10 00:00:19 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `ve...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ve...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ve...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ve...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(23): CodeIgniter\Model->insert(Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->crear()
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-10 00:06:42 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `ve...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ve...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ve...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ve...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(23): CodeIgniter\Model->insert(Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->crear()
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-10 00:18:41 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `cliente...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `cliente...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `cliente...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `cliente...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Clientes.php(46): CodeIgniter\Model->update('1', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Clientes->editar('1')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-10 00:19:06 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `cliente...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `cliente...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `cliente...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `cliente...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Clientes.php(46): CodeIgniter\Model->update('1', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Clientes->editar('1')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-10 00:21:13 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `cliente...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `cliente...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `cliente...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `cliente...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Clientes.php(46): CodeIgniter\Model->update('1', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Clientes->editar('1')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-10 00:24:58 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `cliente...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `cliente...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `cliente...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `cliente...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Clientes.php(46): CodeIgniter\Model->update('1', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Clientes->editar('1')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-10 00:28:37 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `cliente...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `cliente...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `cliente...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `cliente...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Clientes.php(46): CodeIgniter\Model->update('1', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Clientes->editar('1')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-10 00:31:43 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `cliente...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `cliente...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `cliente...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `cliente...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Clientes.php(46): CodeIgniter\Model->update('1', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Clientes->editar('1')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-10 00:33:11 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `cl...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Clientes.php(23): CodeIgniter\Model->insert(Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Clientes->crear()
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-10 00:33:31 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `cl...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Clientes.php(23): CodeIgniter\Model->insert(Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Clientes->crear()
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-10 00:33:43 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `cl...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Clientes.php(23): CodeIgniter\Model->insert(Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Clientes->crear()
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-10 00:35:08 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `cliente...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `cliente...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `cliente...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `cliente...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Clientes.php(46): CodeIgniter\Model->update('1', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Clientes->editar('1')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-10 15:35:24 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `cl...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Clientes.php(23): CodeIgniter\Model->insert(Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Clientes->crear()
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-10 15:35:42 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `cl...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Clientes.php(23): CodeIgniter\Model->insert(Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Clientes->crear()
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-10 15:35:59 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `cliente...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `cliente...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `cliente...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `cliente...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Clientes.php(46): CodeIgniter\Model->update('1', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Clientes->editar('1')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-10 15:36:14 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `cliente...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `cliente...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `cliente...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `cliente...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Clientes.php(46): CodeIgniter\Model->update('1', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Clientes->editar('1')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-10 15:36:18 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `cliente...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `cliente...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `cliente...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `cliente...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Clientes.php(46): CodeIgniter\Model->update('1', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Clientes->editar('1')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-10 15:36:28 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `cliente...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `cliente...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `cliente...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `cliente...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Clientes.php(46): CodeIgniter\Model->update('1', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Clientes->editar('1')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-10 15:39:30 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `cliente...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `cliente...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `cliente...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `cliente...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Clientes.php(46): CodeIgniter\Model->update('1', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Clientes->editar('1')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-10 15:39:32 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `cliente...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `cliente...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `cliente...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `cliente...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Clientes.php(46): CodeIgniter\Model->update('1', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Clientes->editar('1')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-11-10 15:52:59 --> syntax error, unexpected token "public", expecting end of file
in APPPATH\Controllers\API\Clientes.php on line 34.
 1 SYSTEMPATH\Autoloader\Autoloader.php(259): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\API\\Clientes.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(237): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\API\\Clientes')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\API\\Clientes')
 4 SYSTEMPATH\CodeIgniter.php(877): class_exists('\\App\\Controllers\\API\\Clientes', true)
 5 SYSTEMPATH\CodeIgniter.php(469): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-10 15:53:09 --> syntax error, unexpected token "public", expecting end of file
in APPPATH\Controllers\API\Clientes.php on line 34.
 1 SYSTEMPATH\Autoloader\Autoloader.php(259): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\API\\Clientes.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(237): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\API\\Clientes')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\API\\Clientes')
 4 SYSTEMPATH\CodeIgniter.php(877): class_exists('\\App\\Controllers\\API\\Clientes', true)
 5 SYSTEMPATH\CodeIgniter.php(469): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-10 15:53:27 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `cl...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Clientes.php(23): CodeIgniter\Model->insert(Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Clientes->crear()
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-11-10 15:59:03 --> syntax error, unexpected token "}", expecting "elseif" or "else" or "endif"
in APPPATH\Controllers\API\Clientes.php on line 26.
 1 SYSTEMPATH\Autoloader\Autoloader.php(259): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\API\\Clientes.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(237): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\API\\Clientes')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\API\\Clientes')
 4 SYSTEMPATH\CodeIgniter.php(877): class_exists('\\App\\Controllers\\API\\Clientes', true)
 5 SYSTEMPATH\CodeIgniter.php(469): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-10 15:59:09 --> syntax error, unexpected token "}", expecting "elseif" or "else" or "endif"
in APPPATH\Controllers\API\Clientes.php on line 26.
 1 SYSTEMPATH\Autoloader\Autoloader.php(259): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\API\\Clientes.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(237): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\API\\Clientes')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\API\\Clientes')
 4 SYSTEMPATH\CodeIgniter.php(877): class_exists('\\App\\Controllers\\API\\Clientes', true)
 5 SYSTEMPATH\CodeIgniter.php(469): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-10 16:05:32 --> syntax error, unexpected token "catch"
in APPPATH\Controllers\API\Clientes.php on line 32.
 1 SYSTEMPATH\Autoloader\Autoloader.php(259): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\API\\Clientes.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(237): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\API\\Clientes')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\API\\Clientes')
 4 SYSTEMPATH\CodeIgniter.php(877): class_exists('\\App\\Controllers\\API\\Clientes', true)
 5 SYSTEMPATH\CodeIgniter.php(469): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-10 16:05:59 --> syntax error, unexpected token "catch"
in APPPATH\Controllers\API\Clientes.php on line 32.
 1 SYSTEMPATH\Autoloader\Autoloader.php(259): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\API\\Clientes.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(237): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\API\\Clientes')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\API\\Clientes')
 4 SYSTEMPATH\CodeIgniter.php(877): class_exists('\\App\\Controllers\\API\\Clientes', true)
 5 SYSTEMPATH\CodeIgniter.php(469): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-10 16:06:02 --> syntax error, unexpected token "catch"
in APPPATH\Controllers\API\Clientes.php on line 32.
 1 SYSTEMPATH\Autoloader\Autoloader.php(259): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\API\\Clientes.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(237): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\API\\Clientes')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\API\\Clientes')
 4 SYSTEMPATH\CodeIgniter.php(877): class_exists('\\App\\Controllers\\API\\Clientes', true)
 5 SYSTEMPATH\CodeIgniter.php(469): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-10 16:06:22 --> syntax error, unexpected token "catch"
in APPPATH\Controllers\API\Clientes.php on line 32.
 1 SYSTEMPATH\Autoloader\Autoloader.php(259): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\API\\Clientes.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(237): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\API\\Clientes')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\API\\Clientes')
 4 SYSTEMPATH\CodeIgniter.php(877): class_exists('\\App\\Controllers\\API\\Clientes', true)
 5 SYSTEMPATH\CodeIgniter.php(469): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-10 16:07:11 --> syntax error, unexpected token "catch"
in APPPATH\Controllers\API\Clientes.php on line 32.
 1 SYSTEMPATH\Autoloader\Autoloader.php(259): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\API\\Clientes.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(237): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\API\\Clientes')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\API\\Clientes')
 4 SYSTEMPATH\CodeIgniter.php(877): class_exists('\\App\\Controllers\\API\\Clientes', true)
 5 SYSTEMPATH\CodeIgniter.php(469): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-10 16:08:05 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `cl...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Clientes.php(23): CodeIgniter\Model->insert(Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Clientes->crear()
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-10 16:09:21 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `cl...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Clientes.php(23): CodeIgniter\Model->insert(Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Clientes->crear()
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-10 16:10:20 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `cliente...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `cliente...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `cliente...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `cliente...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Clientes.php(46): CodeIgniter\Model->update('1', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Clientes->editar('1')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-10 16:10:31 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `cliente...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `cliente...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `cliente...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `cliente...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Clientes.php(46): CodeIgniter\Model->update('1', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Clientes->editar('1')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-11-10 16:11:27 --> syntax error, unexpected token "}", expecting "elseif" or "else" or "endif"
in APPPATH\Controllers\API\Clientes.php on line 29.
 1 SYSTEMPATH\Autoloader\Autoloader.php(259): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\API\\Clientes.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(237): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\API\\Clientes')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\API\\Clientes')
 4 SYSTEMPATH\CodeIgniter.php(877): class_exists('\\App\\Controllers\\API\\Clientes', true)
 5 SYSTEMPATH\CodeIgniter.php(469): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-10 16:11:34 --> syntax error, unexpected token "}", expecting "elseif" or "else" or "endif"
in APPPATH\Controllers\API\Clientes.php on line 29.
 1 SYSTEMPATH\Autoloader\Autoloader.php(259): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\API\\Clientes.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(237): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\API\\Clientes')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\API\\Clientes')
 4 SYSTEMPATH\CodeIgniter.php(877): class_exists('\\App\\Controllers\\API\\Clientes', true)
 5 SYSTEMPATH\CodeIgniter.php(469): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-10 16:12:25 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `cl...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Clientes.php(23): CodeIgniter\Model->insert(Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Clientes->crear()
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-10 16:12:58 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `cl...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Clientes.php(23): CodeIgniter\Model->insert(Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Clientes->crear()
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-10 16:13:35 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `cl...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Clientes.php(23): CodeIgniter\Model->insert(Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Clientes->crear()
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-11-10 16:15:19 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `cl...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Clientes.php(23): CodeIgniter\Model->insert(Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Clientes->crear()
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
